---
# Temporary unencrypted secrets for deployment

vault_github_username: bunchc
vault_github_token: dummy_token_not_needed_for_local_build

vault_mqtt_password: /yameCjLOFwbskcltRRZZUBWFBg/Q+PAIPNZZz7Kgpg=

vault_central_api_secret_key: dev_secret_key_123

vault_db_password: dev_password
